strict-sigcheck = false

[YouTube]
brand = "morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"

[YT-Music]
brand = "morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
